### ISSUE TITLE
preconditions in step

### ISSUE THREAD

**Issue by timukas** [ErdemOzgen/blackdagger#80]
Hi,

I'm trying to use **preconditions** in step, but stuck with its logic.

In 1st step i'm running "ip a" to get IP address of eth0.

```
steps:
  - name: "Check IP"
    description: "IP must be in 192.168.111.0/24"
    command: bash
    script: ip -f inet addr show eth0 | grep -Po 'inet \K[\d.]+'
    output: IP_CHECK

```
Now in second step i want to check if IP belongs to abovementioned step

```
    preconditions:
      - condition: "${IP_CHECK}"
        expected: "192.168.111."

```

Since IP_CHECK variable has value "192.168.111.111", then "expected" does not work with partial values.

Any hints on how to check partial match?

**Comment by timukas** [comment]
This is what i have in logs:

`condition was not met. Condition=${IP_CHECK} Expected=192.168.111 Actual=192.168.111.111`

**Comment by ErdemOzgen** [comment]
Working on it @ataseren can you handle this one ?

**Comment by ataseren** [comment]
Hello @timukas,  good catch! We are going to add this mechanism, along with many other features in our new version. It will be released in this week.

**Comment by ErdemOzgen** [comment]
@timukas @ataseren Necessary additions have been made in the source code, Docker containers and Blackcart Docker containers have been updated, and the issue mentioned in version 1.1.0 has been resolved.

**Comment by timukas** [comment]
I've downloaded from this repo latest single binary of blackdagger v1.1.0 (linux amd64) and partial match still does not work.

I see this error in blackdagger ui:

```
| condition was not met. Condition=${IP_CHECK} Expected=192.168.111. Actual=192.168.111.44 |
```

**Comment by ataseren** [comment]
Hello again @timukas. In v1.1.0, we added regex capabilities for preconditions. Therefore, you must use a regex to perform such partial match. To make the program see the condition as a regex value, you must add `re:` at its beginning. For example:

```yaml
    preconditions:
      - condition: "${IP_CHECK}"
        expected: "re:192.168.111.*"
```

With this modification, every IP that starts with "192.168.111" will cause condition to be valid.

**Comment by ErdemOzgen** [comment]
@timukas also we have just updated docs : https://blackdagger.readthedocs.io/en/latest/yaml_format.html#id10

See in Adding conditional logic section

**Comment by timukas** [comment]
Awesome! Now all works as it should!
